version: 2.1

jobs:
  my_first_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          command: echo "test" > test.txt
      - run:
          command: cat test.txt

  my_second_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          command: cat test.txt

workflows:
  test_workflow:
    jobs:
      - my_first_job
      - my_second_job
